# ingredients.py

# --- OILY SKIN INGREDIENTS ---
best_oily = ['camellia sinensis', 'epigallocatechin gallate', 'glucosamine', 'green tea', 'oleyl adapalenate', 'retinal', 'spiraea ulmaria extract', 'triethyl citrate', 'zinc oxide']
good_oily = ['aluminum hydroxide', 'aluminum magnesium silicate', 'aluminum starch octenylsuccinate', 'bentonite', 'calcium carbonate', 'charcoal', 'charcoal powder', 'cornstarch', 'dextrin', "fuller's earth", 'hectorite', 'hydrolyzed corn starch', 'illite', 'kaolin', 'magnesium', 'magnesium aluminum silicate', 'magnesium carbonate', 'magnesium hydroxide', 'maltodextrin', 'methyl methacrylate/glycol dimethacrylate crosspolymer', 'montmorillonite', 'nylon-12', 'rice starch', 'silica', 'silicate', 'silicone', 'silk powder', 'sodium polyacrylate', 'sodium polyacrylate starch', 'tapioca starch', 'zea mays corn starch']
v1_oily_ingredients = best_oily + good_oily

# --- WRINKLE INGREDIENTS ---
best_wrinkle = ['3-o ethyl ascorbic acid', 'acai', 'acerola fruit extract', 'acetyl cysteine', 'acetyl dipeptide-1 cetyl ester', 'acetyl glucosamine', 'acetyl hexapeptide-1', 'acetyl hexapeptide-37', 'acetyl hexapeptide-8', 'acetyl sh-hexapeptide-5 amide acetate', 'acetyl tetrapeptide-11', 'acetyl tetrapeptide-5', 'acetyl tetrapeptide-9', 'achillea millefolium extract', 'actinidia chinensis (kiwi) fruit extract', 'adansonia digitata seed extract', 'adansonia digitata seed oil', 'adenosine triphosphate', 'aha', 'akebia quinata (chocolate vine) stem extract', 'alaria esculenta extract', 'albatrellus confluens (mushroom) extract', 'aleurites moluccana seed oil', 'alfalfa extract', 'algae', 'algae extract', 'almond/borage/linseed/olive acids glycerides', 'aloe barbadensis leaf juice powder', 'alpha-arbutin', 'alpha bisabolol', 'alpha-glucan oligosaccharide', 'alpha hydroxy acid', 'alpha lipoic acid', 'alpha-tocopherol', 'althaea officinalis root extract', 'amaranthus caudatus seed extract', 'ammonium glycolate', 'anastatica hierochuntica extract', 'anthemis nobilis flower extract']
good_wrinkle = ['acacia seyal gum extract', 'acer saccharum extract', 'acetylarginyltryptophyl diphenylglycine', 'acetyl methionine', 'acetyl octapeptide-3', 'aesculus hippocastanum', 'agastache mexicana (hyssop) flower/leaf/stem extract', 'agastache mexicana flower/leaf/stem extract', 'ahnfeltia concinna extract', 'alanine', 'albizia julibrissin bark extract', 'algin', 'amino esters-1', 'aminopropyl ascorbyl phosphate', 'amygdalic acid', 'anacyclus pyrethrum root extract', 'ananas sativus fruit extract', 'andiroba oil', 'annato extract', 'annona cherimola fruit extract', 'anogeissus leiocarpus bark extract']
v1_wrinkle_ingredients = best_wrinkle + good_wrinkle

# --- ACNE INGREDIENTS ---
best_acne = ['azelaic acid', 'azelex', 'benzoyl peroxide', 'beta hydroxy acid', 'bha (beta hydroxy acid)', 'camellia sinensis', 'cannabidiol', 'capryloyl salicylic acid', 'epigallocatechin gallate', 'glucosamine', 'green tea', 'hydroquinone', 'hydroxypinacolone retinoate', 'niacinamide', 'nicotinamide', 'nicotinic acid', 'oleyl adapalenate', 'pelvetia canaliculata extract', 'rehmannia glutinosa root extract', 'retinal', 'retinoids', 'retinol', 'retinyl ascorbate', 'retinyl propionate', 'retinyl retinoate', 'rhodiola rosea root extract', 'salicylic acid', 'spiraea ulmaria extract', 'tetrapeptide-30', 'tocopheryl succinate', 'triethyl citrate', 'vitamin a', 'vitamin b3', 'zinc oxide']
good_acne = ['aluminum hydroxide', 'aluminum magnesium silicate', 'aluminum starch octenylsuccinate', 'aminopropyl ascorbyl phosphate', 'bentonite', 'betaine salicylate', 'calcium carbonate', 'chamaecyparis obtusa leaf extract', 'charcoal', 'charcoal powder', 'cornstarch', 'dextrin', "fuller's earth", 'hectorite', 'hydrolyzed corn starch', 'illite', 'kaolin', 'kojyl methylenedioxycinnamate', 'maclura cochinchinensis leaf prenyl flavonoids', 'magnesium', 'magnesium aluminum silicate', 'magnesium carbonate', 'magnesium hydroxide', 'maltodextrin', 'methyl methacrylate/glycol dimethacrylate crosspolymer', 'montmorillonite', 'nylon-12', 'octadecenedioic acid', 'pyridoxine hydrochloride (hcl)', 'rice starch', 'silica', 'silicate', 'silicone', 'silk powder', 'skeletonema costatum extract', 'sodium polyacrylate', 'sodium polyacrylate starch', 'succinic acid', 'tapioca starch', 'zea mays corn starch']
v1_acne_ingredients = best_acne + good_acne

# --- DRY SKIN INGREDIENTS ---
best_dry = ['acai', 'acetyl carnitine hcl', 'acetyl cysteine', 'acetyl glucosamine', 'acetyl hexapeptide-1', 'acetyl hexapeptide-37', 'acetyl hexapeptide-8', 'acetyl tetrapeptide-11', 'acetyl tetrapeptide-5', 'achillea millefolium extract', 'adansonia digitata seed extract', 'adansonia digitata seed oil', 'adenosine', 'adenosine phosphate', 'adenosine triphosphate', 'aha', 'ahnfeltiopsis concinna extract', 'akebia quinata (chocolate vine) stem extract', 'alaria esculenta extract', 'albatrellus confluens (mushroom) extract', 'aleurites moluccana seed oil', 'algae', 'algae extract', 'allantoin', 'allantoin glycyrrhetinic acid', 'almond/borage/linseed/olive acids glycerides', 'almond oil', 'aloe barbadensis', 'aloe barbadensis leaf extract', 'aloe barbadensis leaf juice', 'aloe barbadensis leaf juice extract', 'aloe extract', 'aloe juice', 'aloe vera', 'alpha bisabolol', 'alpha-glucan', 'alpha-glucan oligosaccharide', 'alpha hydroxy acid', 'althaea officinalis', 'althaea officinalis root extract', 'amaranthus caudatus seed extract', 'amino acids', 'anastatica hierochuntica extract', 'anthemis nobilis flower extract', 'anthocyanin', 'antioxidant', 'apple fruit extract', 'apricot kernel oil', 'arachis hypogaea extract', 'arctium lappa', 'arctium lappa root extract', 'arctium majus', 'arctium majus root extract', 'arctostaphylos uva ursi leaf extract', 'argania spinosa kernel oil', 'argan oil', 'arginine', 'arginine/lysine polypeptide', 'argireline', 'ascorbyl methylsilanol pectinate', 'aspergillus ferment', 'astaxanthin', 'astaxanthin extract', 'atp', 'atractylodes macrocephala root powder', 'avena sativa (oat) kernel extract', 'avena sativa (oat) kernel oil', 'avena sativa kernel extract', 'avocado oil', 'azelaic acid', 'azelaoyl bis-dipeptide-10', 'azelex', 'babassu oil', 'bacillus ferment', 'baicalin', 'bakuchiol', 'balloon vine extract', 'barberry']
good_dry = ['1, 2-hexanediol', '10-hydroxydecanoic acid', '2,3-butanediol', 'acacia senegal gum', 'acacia seyal gum extract', 'acetylarginyltryptophyl diphenylglycine', 'acetylated castor oil', 'acetylated hydrogenated cottonseed glyceride', 'acetylated lanolin', 'acetylated lanolin alcohol', 'acetylated palm kernel glycerides', 'acetyl glutamine', 'acetyl glyceryl ricinoleate', 'acetyl methionine', 'acetyl octapeptide-3', 'acetyl tyrosine', 'acrylates copolymer', 'aesculus hippocastanum', 'agar', 'ahnfeltia concinna extract', 'ahnfeltia extract', 'alanine', 'algin', 'aliphatic hydrocarbon', 'alteromonas ferment extract', 'althaea rosea', 'aminobutyric acid', 'ammonium acryloyldimethyltaurate/vp copolymer', 'ammonium glycyrrhizate', 'amodimethicone', 'anacyclus pyrethrum root extract', 'anacystis nidulans extract', 'andiroba oil', 'anhydroxylitol', 'annona cherimola fruit extract', 'apium gravele_ns (celery) seed extract', 'aqua/water/eau', 'arachidic acid', 'arachidyl alcohol', 'arachidyl propionate', 'arachis hypogaea (peanut) oil', 'artemisia annua extract', 'ascophyllum nodosum', 'asiaticoside', 'aspalathus linearis extract', 'asparagine', 'asparagopsis armata extract', 'aspartic acid', 'astrocaryum murumuru seed butter', 'atelocollagen', 'azulene', 'banana extract', 'batyl alcohol']
v1_dry_skin_ingredients = best_dry + good_dry

# --- FINAL KEY INGREDIENTS DICTIONARY ---
KEY_INGREDIENTS = {
    'acne': v1_acne_ingredients,
    'wrinkles': v1_wrinkle_ingredients,
    'dry': v1_dry_skin_ingredients,
    'oily': v1_oily_ingredients
}
# --- RED FLAGS (Add these to ingredients.py) ---

# Ingredients that clog pores (Avoid for Acne/Oily)
COMEDOGENIC_REAGENTS = [
    'coconut oil', 'isopropyl myristate', 'isopropyl palmitate', 
    'lanolin', 'algae extract', 'sodium chloride', 'stearic acid'
]

# Ingredients that irritate sensitive or dry skin
POTENTIAL_IRRITANTS = [
    'denatured alcohol', 'fragrance', 'parfum', 'menthol', 
    'eucalyptus oil', 'lemon oil', 'sodium lauryl sulfate'
]